export const data = [
    {id: 1,
        first_name: 'surendar',
        last_name: 'kalyanam',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'sure@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 2,
        first_name: 'sudhakar',
        last_name: 'kalyanam',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'sudha@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 3,
        first_name: 'vijay',
        last_name: ' ',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vijay@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 4,
        first_name: 'Vinoth',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 5,
        first_name: 'Kalai',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 6,
        first_name: 'Saravanan',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 7,
        first_name: 'Vicky',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 8,
        first_name: 'Kalpana',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 9,
        first_name: 'kalyanam',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 10,
        first_name: 'Arun',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 11,
        first_name: 'Aruna',
        last_name: 'k',
        middle_name: ' ',
        phone_number_one: 9344444494,
        phone_number_two: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanent_address: 'No:123, Main Street, Villpuram',
        alternate_address: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    }
];

