export const data = [
    {id: 1,
        firstName: 'surendar',
        lastName: 'kalyanam',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'sure@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 2,
        firstName: 'sudhakar',
        lastName: 'kalyanam',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'sudha@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 3,
        firstName: 'vijay',
        lastName: ' ',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vijay@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 4,
        firstName: 'Vinoth',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 5,
        firstName: 'Kalai',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 6,
        firstName: 'Saravanan',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 7,
        firstName: 'Vicky',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 8,
        firstName: 'Kalpana',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 9,
        firstName: 'kalyanam',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 10,
        firstName: 'Arun',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    },
    {   id: 11,
        firstName: 'Aruna',
        lastName: 'k',
        middleName: ' ',
        phoneNumberOne: 9344444494,
        phoneNumberTwo: 9896666666,
        dob: '30/01/1993',
        age: 12,
        email: 'vino@gmail.com',
        permanentAddress: 'No:123, Main Street, Villpuram',
        alternateAddress: 'No:232 , Sub Main Street, Villupuram',
        avatar: 'https://semantic-ui.com/images/avatar/large/elliot.jpg'
    }
];

