export const data = [
    {   id:1,
        first_name:"surendar",
        last_name:"kalyanam",
        middle_name:" ",
        phone_number_one:9344444494,
        phone_number_two:9896666666,
        dob:"30/01/1993",
        age:12,
        email:"sure@gmail.com",
        permanent_address:"No:123, Main Street, Villpuram",
        alternate_address:"No:232 , Sub Main Street, Villupuram",
        avator:"https://semantic-ui.com/images/avatar/small/elliot.jpg"
    },
    {   id:2,
        first_name:"sudhakar",
        last_name:"kalyanam",
        middle_name:" ",
        phone_number_one:9344444494,
        phone_number_two:9896666666,
        dob:"30/01/1993",
        age:12,
        email:"sudha@gmail.com",
        permanent_address:"No:123, Main Street, Villpuram",
        alternate_address:"No:232 , Sub Main Street, Villupuram",
        avator:"https://semantic-ui.com/images/avatar/small/elliot.jpg"
    },
    {   id:3,
        first_name:"vijay",
        last_name:" ",
        middle_name:" ",
        phone_number_one:9344444494,
        phone_number_two:9896666666,
        dob:"30/01/1993",
        age:12,
        email:"vijay@gmail.com",
        permanent_address:"No:123, Main Street, Villpuram",
        alternate_address:"No:232 , Sub Main Street, Villupuram",
        avator:"https://semantic-ui.com/images/avatar/small/elliot.jpg"
    },
    {   id:4,
        first_name:"Vinoth",
        last_name:"k",
        middle_name:" ",
        phone_number_one:9344444494,
        phone_number_two:9896666666,
        dob:"30/01/1993",
        age:12,
        email:"vino@gmail.com",
        permanent_address:"No:123, Main Street, Villpuram",
        alternate_address:"No:232 , Sub Main Street, Villupuram",
        avator:"https://semantic-ui.com/images/avatar/small/elliot.jpg"
    },
];